console.log('1. Starting isolation check');
import { ConfigService } from './src/services/ConfigService.js';
console.log('2. ConfigService loaded');
import initializeContext from './src/lib/context.js';
console.log('3. context loaded');
import MultiTenantApp from './src/server/multiTenantApp.js';
console.log('4. MultiTenantApp loaded');
import { getCampaignWorker } from './src/jobs/campaignWorker.js';
console.log('5. campaignWorker loaded');
console.log('Done');
