#!/bin/bash

# WhatsDeX AI Bot - Render.com Deployment Script
# Deploy to Render with infrastructure as code

set -e

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

print_status() {
    echo -e "${BLUE}[RENDER]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Configuration
PROJECT_NAME="whatsdx-ai-bot"
ENVIRONMENT=${1:-"production"}

print_status "Starting Render deployment for WhatsDeX AI Bot"
print_status "Environment: $ENVIRONMENT"

# Check prerequisites
check_prerequisites() {
    print_status "Checking prerequisites..."
    
    # Check if git is available
    if ! command -v git &> /dev/null; then
        print_error "Git is required for Render deployment"
        exit 1
    fi
    
    # Check if we're in a git repository
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        print_error "This must be run from a Git repository"
        exit 1
    fi
    
    print_success "Prerequisites check passed"
}

# Setup Render configuration
setup_render_config() {
    print_status "Setting up Render configuration..."
    
    # Copy render.yaml to root
    cp deployment/cloud-platforms/render/render.yaml ./render.yaml
    
    # Create Render-specific start script
    cat > start-render.js << 'EOF'
// Render.com start script for WhatsDeX AI Bot
const { spawn } = require('child_process');
const path = require('path');

console.log('🚀 Starting WhatsDeX AI Bot on Render...');

// Environment check
if (!process.env.DATABASE_URL) {
    console.error('❌ DATABASE_URL not set');
    process.exit(1);
}

if (!process.env.REDIS_URL) {
    console.error('❌ REDIS_URL not set');
    process.exit(1);
}

// Start the main application
const mainProcess = spawn('node', ['main.js'], {
    stdio: 'inherit',
    env: {
        ...process.env,
        PORT: process.env.PORT || 10000,
        NODE_ENV: 'production',
        RENDER_DEPLOYMENT: 'true'
    }
});

mainProcess.on('exit', (code) => {
    console.log(`Main process exited with code ${code}`);
    process.exit(code);
});

// Handle graceful shutdown
process.on('SIGTERM', () => {
    console.log('🛑 Received SIGTERM, shutting down gracefully...');
    mainProcess.kill('SIGTERM');
});

process.on('SIGINT', () => {
    console.log('🛑 Received SIGINT, shutting down gracefully...');
    mainProcess.kill('SIGINT');
});
EOF

    # Update package.json for Render
    if [ -f package.json ]; then
        # Create backup
        cp package.json package.json.backup
        
        # Add Render-specific scripts
        npm pkg set scripts.render:build="npm install && npm run generate"
        npm pkg set scripts.render:start="node start-render.js"
        npm pkg set scripts.build="npm run generate"
        npm pkg set engines.node=">=18.0.0"
    fi
    
    print_success "Render configuration setup completed"
}

# Create environment variables guide
create_env_guide() {
    print_status "Creating environment variables guide..."
    
    cat > RENDER_ENV_SETUP.md << 'EOF'
# Render Environment Variables Setup

After deploying to Render, you need to set these environment variables in the Render dashboard:

## Required API Keys (Set manually in Render dashboard)

### AI Services
- `GEMINI_API_KEY` - Your Google Gemini API key
- `META_AI_KEY` - Your Meta AI API key (optional)
- `OPENAI_API_KEY` - Your OpenAI API key (optional)

### External APIs
- `YOUTUBE_API_KEY` - YouTube Data API key
- `WEATHER_API_KEY` - Weather service API key
- `GOOGLE_SEARCH_API_KEY` - Google Custom Search API key
- `GOOGLE_SEARCH_ENGINE_ID` - Google Custom Search Engine ID

### Webhooks & Notifications
- `SLACK_WEBHOOK_URL` - Slack webhook for notifications (optional)

## Auto-Generated Variables (Render will generate these)
- `JWT_SECRET` - Automatically generated by Render
- `NEXTAUTH_SECRET` - Automatically generated by Render
- `DATABASE_URL` - Automatically set from PostgreSQL service
- `REDIS_URL` - Automatically set from Redis service

## To set variables in Render:
1. Go to your service dashboard
2. Click "Environment" tab
3. Add each variable with its value
4. Deploy to apply changes

## Testing Deployment:
- Main API: https://api-whatsdx.onrender.com/api/health
- Dashboard: https://dashboard-whatsdx.onrender.com
EOF

    print_success "Environment setup guide created: RENDER_ENV_SETUP.md"
}

# Deploy to Render
deploy_to_render() {
    print_status "Deploying to Render..."
    
    # Commit render.yaml to git
    git add render.yaml start-render.js RENDER_ENV_SETUP.md
    git commit -m "Add Render deployment configuration" || true
    
    print_success "Render configuration committed to Git"
    
    # Instructions for Render deployment
    echo ""
    print_status "=== RENDER DEPLOYMENT INSTRUCTIONS ==="
    echo ""
    echo "1. 🌐 Go to https://render.com and sign in"
    echo "2. 📁 Click 'New' → 'Blueprint'"
    echo "3. 🔗 Connect your GitHub repository"
    echo "4. 📄 Select the repository containing this code"
    echo "5. 🎯 Render will automatically detect render.yaml"
    echo "6. 🚀 Click 'Apply' to deploy all services"
    echo ""
    print_warning "Important: Set the required environment variables in Render dashboard"
    echo "📖 See RENDER_ENV_SETUP.md for details"
    echo ""
    print_status "Expected services to be created:"
    echo "  - whatsdx-ai-bot (Main API)"
    echo "  - whatsdx-dashboard (Web Dashboard)"
    echo "  - whatsdx-worker (Background Worker)"
    echo "  - whatsdx-cron (Scheduled Jobs)"
    echo "  - whatsdx-postgres (Database)"
    echo "  - whatsdx-redis (Cache)"
    echo ""
}

# Monitor deployment
monitor_deployment() {
    print_status "Deployment monitoring setup..."
    
    cat > check-render-deployment.sh << 'EOF'
#!/bin/bash

echo "🔍 Checking Render deployment status..."

# Check main API
if curl -f https://api-whatsdx.onrender.com/api/health &>/dev/null; then
    echo "✅ Main API is healthy"
else
    echo "❌ Main API is not responding"
fi

# Check dashboard
if curl -f https://dashboard-whatsdx.onrender.com &>/dev/null; then
    echo "✅ Dashboard is accessible"
else
    echo "❌ Dashboard is not responding"
fi

echo ""
echo "🔗 Access URLs:"
echo "  - API: https://api-whatsdx.onrender.com"
echo "  - Dashboard: https://dashboard-whatsdx.onrender.com"
echo "  - Health Check: https://api-whatsdx.onrender.com/api/health"
EOF

    chmod +x check-render-deployment.sh
    
    print_success "Deployment monitoring script created: check-render-deployment.sh"
}

# Cleanup
cleanup() {
    print_status "Cleaning up temporary files..."
    
    # Restore original package.json if backup exists
    if [ -f package.json.backup ]; then
        mv package.json.backup package.json
    fi
    
    print_success "Cleanup completed"
}

# Main execution
main() {
    check_prerequisites
    setup_render_config
    create_env_guide
    deploy_to_render
    monitor_deployment
    
    print_success "Render deployment preparation completed!"
    
    echo ""
    print_status "🎯 Next Steps:"
    echo "1. Go to https://render.com and create Blueprint deployment"
    echo "2. Set environment variables using RENDER_ENV_SETUP.md"
    echo "3. Run ./check-render-deployment.sh to verify deployment"
    echo "4. Monitor logs in Render dashboard"
    echo ""
    print_success "Happy deploying! 🚀"
}

# Error handling
trap 'print_error "Render deployment script failed at line $LINENO"' ERR

# Run main function
main "$@"