#!/bin/bash

# WhatsDeX AI Bot - Railway Deployment Script
# Deploy to Railway with modern deployment practices

set -e

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

print_status() {
    echo -e "${BLUE}[RAILWAY]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

PROJECT_NAME=${1:-"whatsdx-ai-bot"}
ENVIRONMENT=${2:-"production"}

print_status "Starting Railway deployment for WhatsDeX AI Bot"
print_status "Project: $PROJECT_NAME"
print_status "Environment: $ENVIRONMENT"

# Check prerequisites
check_prerequisites() {
    print_status "Checking prerequisites..."
    
    # Check Railway CLI
    if ! command -v railway &> /dev/null; then
        print_warning "Railway CLI not found. Installing..."
        npm install -g @railway/cli
    fi
    
    # Check if logged in
    if ! railway whoami &> /dev/null; then
        print_status "Please log in to Railway"
        railway login
    fi
    
    print_success "Prerequisites check passed"
}

# Setup Railway project
setup_railway_project() {
    print_status "Setting up Railway project..."
    
    # Initialize Railway project
    if [ ! -f railway.json ]; then
        cp deployment/cloud-platforms/railway/railway.json ./railway.json
        print_status "Railway configuration copied"
    fi
    
    # Link to existing project or create new one
    if ! railway status &> /dev/null; then
        print_status "Linking to Railway project..."
        railway link || railway login
    fi
    
    print_success "Railway project setup completed"
}

# Setup environment variables
setup_environment() {
    print_status "Setting up environment variables..."
    
    # Core variables
    railway variables set NODE_ENV=production
    railway variables set AI_INTELLIGENCE_MODE=true
    railway variables set ANALYTICS_ENABLED=true
    railway variables set RAILWAY_DEPLOYMENT=true
    railway variables set LOG_LEVEL=info
    
    # Generate secrets
    JWT_SECRET=$(openssl rand -base64 32)
    NEXTAUTH_SECRET=$(openssl rand -base64 32)
    
    railway variables set JWT_SECRET="$JWT_SECRET"
    railway variables set NEXTAUTH_SECRET="$NEXTAUTH_SECRET"
    
    print_success "Basic environment variables set"
    
    # Create environment setup guide
    cat > RAILWAY_ENV_SETUP.md << 'EOF'
# Railway Environment Variables Setup

Set these environment variables in Railway dashboard or CLI:

## Required API Keys
```bash
# AI Services
railway variables set GEMINI_API_KEY=your_gemini_api_key
railway variables set META_AI_KEY=your_meta_ai_key
railway variables set OPENAI_API_KEY=your_openai_api_key

# External APIs
railway variables set YOUTUBE_API_KEY=your_youtube_api_key
railway variables set WEATHER_API_KEY=your_weather_api_key
railway variables set GOOGLE_SEARCH_API_KEY=your_google_search_key
railway variables set GOOGLE_SEARCH_ENGINE_ID=your_search_engine_id

# Optional: Notifications
railway variables set SLACK_WEBHOOK_URL=your_slack_webhook
```

## Database URLs (Auto-generated by Railway)
- DATABASE_URL - PostgreSQL connection string
- REDIS_URL - Redis connection string

## Testing Deployment
- Main API: Check Railway dashboard for assigned URL
- Health endpoint: YOUR_RAILWAY_URL/api/health
EOF

    print_success "Environment setup guide created: RAILWAY_ENV_SETUP.md"
}

# Setup Railway services
setup_services() {
    print_status "Setting up Railway services..."
    
    # Add PostgreSQL
    print_status "Adding PostgreSQL database..."
    railway add --database postgresql || true
    
    # Add Redis
    print_status "Adding Redis cache..."
    railway add --database redis || true
    
    # Create railway.toml for service configuration
    cat > railway.toml << 'EOF'
[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run generate && npm run build"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[deploy.healthcheck]]
path = "/api/health"
timeout = 30
interval = 60

[environment]
NODE_ENV = "production"
AI_INTELLIGENCE_MODE = "true"
ANALYTICS_ENABLED = "true"
RAILWAY_DEPLOYMENT = "true"
EOF

    print_success "Railway services setup completed"
}

# Deploy to Railway
deploy_to_railway() {
    print_status "Deploying to Railway..."
    
    # Update package.json for Railway
    npm pkg set scripts.railway:build="npm install && npm run generate"
    npm pkg set scripts.railway:start="npm start"
    npm pkg set scripts.build="npm run generate"
    
    # Create Railway-specific start script
    cat > railway-start.js << 'EOF'
// Railway start script for WhatsDeX AI Bot
const { spawn } = require('child_process');

console.log('🚀 Starting WhatsDeX AI Bot on Railway...');

// Validate environment
if (!process.env.DATABASE_URL) {
    console.error('❌ DATABASE_URL not found');
    process.exit(1);
}

if (!process.env.REDIS_URL) {
    console.error('❌ REDIS_URL not found');
    process.exit(1);
}

console.log('✅ Environment validation passed');

// Start application
const app = spawn('node', ['main.js'], {
    stdio: 'inherit',
    env: {
        ...process.env,
        PORT: process.env.PORT || 3000
    }
});

app.on('exit', (code) => {
    console.log(`Application exited with code ${code}`);
    process.exit(code);
});

// Graceful shutdown
process.on('SIGTERM', () => {
    console.log('🛑 Received SIGTERM, shutting down...');
    app.kill('SIGTERM');
});
EOF

    # Add files to git and deploy
    git add railway.json railway.toml railway-start.js RAILWAY_ENV_SETUP.md package.json
    git commit -m "Add Railway deployment configuration" || true
    
    # Deploy to Railway
    print_status "Deploying to Railway..."
    railway up
    
    print_success "Railway deployment completed!"
}

# Monitor deployment
monitor_deployment() {
    print_status "Monitoring deployment..."
    
    # Get deployment status
    railway status
    
    # Get service URL
    RAILWAY_URL=$(railway domain 2>/dev/null || echo "Check Railway dashboard for URL")
    
    # Create monitoring script
    cat > check-railway-deployment.sh << 'EOF'
#!/bin/bash

echo "🔍 Checking Railway deployment..."

# Get Railway URL
RAILWAY_URL=$(railway domain 2>/dev/null || echo "unknown")

if [ "$RAILWAY_URL" != "unknown" ]; then
    echo "🔗 Railway URL: $RAILWAY_URL"
    
    # Health check
    if curl -f "$RAILWAY_URL/api/health" &>/dev/null; then
        echo "✅ Health check passed"
    else
        echo "❌ Health check failed"
    fi
else
    echo "ℹ️  Check Railway dashboard for deployment URL"
fi

# Show logs
echo ""
echo "📊 Recent logs:"
railway logs --tail 10
EOF

    chmod +x check-railway-deployment.sh
    
    print_success "Deployment monitoring setup completed"
    
    echo ""
    print_status "🎉 Railway Deployment Summary:"
    echo "  - Project: $PROJECT_NAME"
    echo "  - URL: $RAILWAY_URL"
    echo "  - Status: $(railway status --json | grep -o '"status":"[^"]*' | cut -d'"' -f4 2>/dev/null || echo 'Check dashboard')"
    echo ""
    
    print_status "📋 Next Steps:"
    echo "1. Set API keys using commands in RAILWAY_ENV_SETUP.md"
    echo "2. Check deployment: ./check-railway-deployment.sh"
    echo "3. View logs: railway logs"
    echo "4. Monitor metrics: railway dashboard"
    echo ""
}

# Cleanup
cleanup() {
    print_status "Cleaning up..."
    rm -f railway-start.js
    print_success "Cleanup completed"
}

# Main execution
main() {
    check_prerequisites
    setup_railway_project
    setup_environment
    setup_services
    deploy_to_railway
    monitor_deployment
    cleanup
    
    print_success "Railway deployment completed successfully! 🚀"
}

# Error handling
trap 'print_error "Railway deployment failed at line $LINENO"' ERR

# Show help
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Railway Deployment Script for WhatsDeX AI Bot"
    echo ""
    echo "Usage: $0 [PROJECT_NAME] [ENVIRONMENT]"
    echo ""
    echo "Arguments:"
    echo "  PROJECT_NAME - Railway project name (default: whatsdx-ai-bot)"
    echo "  ENVIRONMENT  - Deployment environment (default: production)"
    echo ""
    exit 0
fi

# Run main function
main "$@"