global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'whatsdex-bot'
    static_configs:
      - targets: ['whatsdex:3000']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'whatsdex-dashboard'
    static_configs:
      - targets: ['dashboard:3000']
    scrape_interval: 10s

  - job_name: 'whatsdex-admin-backend'
    static_configs:
      - targets: ['admin-backend:3001']
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s