# ISO 27001 Compliance Configuration for WhatsDeX AI Bot
# Information Security Management System (ISMS) compliance

apiVersion: v1
kind: ConfigMap
metadata:
  name: iso27001-compliance-config
  namespace: whatsdx-ai
  labels:
    compliance: iso27001
    regulation: international
data:
  iso27001-config.json: |
    {
      "iso27001": {
        "enabled": true,
        "version": "ISO/IEC 27001:2022",
        "certificationBody": "Your Certification Body",
        "certificateNumber": "ISO27001-CERT-2024-001",
        "validFrom": "2024-01-01",
        "validUntil": "2027-01-01",
        "isms": {
          "scope": "WhatsDeX AI Bot Information Processing System",
          "applicableControls": "Annex A controls as applicable",
          "riskTreatmentPlan": "documented",
          "managementReview": "annual",
          "internalAudit": "annual",
          "continuousImprovement": true
        },
        "informationSecurityPolicy": {
          "approved": true,
          "communicatedToAllPersonnel": true,
          "reviewPeriod": "annual",
          "lastReview": "2024-01-01",
          "nextReview": "2025-01-01"
        },
        "organizationOfInformationSecurity": {
          "securityCommittee": true,
          "informationSecurityRoles": "defined",
          "contactWithAuthorities": "established",
          "contactWithSpecialInterestGroups": "maintained"
        },
        "humanResourceSecurity": {
          "securityScreening": true,
          "confidentialityAgreements": true,
          "securityAwareness": "mandatory",
          "disciplinaryProcess": "defined",
          "terminationResponsibilities": "documented"
        },
        "assetManagement": {
          "assetInventory": "maintained",
          "assetClassification": "implemented",
          "acceptableUsePolicy": "enforced",
          "returnOfAssets": "mandatory",
          "informationClassification": "defined"
        },
        "accessControl": {
          "accessControlPolicy": "implemented",
          "userAccessManagement": "formal",
          "privilegedAccessRights": "controlled",
          "passwordManagement": "enforced",
          "accessRights": "reviewed",
          "remoteAccess": "secured"
        }
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iso27001-annex-a-controls
  namespace: whatsdx-ai
  labels:
    compliance: iso27001
    type: controls
data:
  annex-a-controls.json: |
    {
      "organizationalControls": {
        "A.5.1": {
          "control": "Policies for information security",
          "implementation": "Information security policies defined and approved by management",
          "status": "implemented",
          "evidence": ["policy_documents", "approval_records", "communication_records"]
        },
        "A.5.2": {
          "control": "Information security roles and responsibilities",
          "implementation": "Security roles and responsibilities assigned and communicated",
          "status": "implemented",
          "evidence": ["role_definitions", "responsibility_matrix", "job_descriptions"]
        },
        "A.5.3": {
          "control": "Segregation of duties",
          "implementation": "Conflicting duties and responsibilities segregated",
          "status": "implemented",
          "evidence": ["access_control_matrix", "role_separation_documentation"]
        }
      },
      "peopleControls": {
        "A.6.1": {
          "control": "Screening",
          "implementation": "Background verification checks for all personnel",
          "status": "implemented",
          "evidence": ["screening_procedures", "verification_records"]
        },
        "A.6.2": {
          "control": "Terms and conditions of employment",
          "implementation": "Security responsibilities included in employment terms",
          "status": "implemented",
          "evidence": ["employment_contracts", "confidentiality_agreements"]
        },
        "A.6.3": {
          "control": "Information security awareness, education and training",
          "implementation": "Regular security awareness training for all personnel",
          "status": "implemented",
          "evidence": ["training_records", "awareness_campaigns", "competency_assessments"]
        }
      },
      "physicalAndEnvironmentalControls": {
        "A.7.1": {
          "control": "Physical security perimeters",
          "implementation": "Secure areas protected by appropriate entry controls",
          "status": "implemented",
          "evidence": ["facility_security_plans", "access_logs", "security_cameras"]
        },
        "A.7.2": {
          "control": "Physical entry",
          "implementation": "Access to secure areas controlled and monitored",
          "status": "implemented",
          "evidence": ["access_control_systems", "visitor_logs", "entry_procedures"]
        },
        "A.7.3": {
          "control": "Protection against environmental threats",
          "implementation": "Equipment protected from environmental hazards",
          "status": "implemented",
          "evidence": ["environmental_controls", "monitoring_systems", "incident_logs"]
        }
      },
      "technologicalControls": {
        "A.8.1": {
          "control": "User endpoint devices",
          "implementation": "Endpoint devices properly secured and managed",
          "status": "implemented",
          "evidence": ["device_management_policies", "security_configurations", "compliance_reports"]
        },
        "A.8.2": {
          "control": "Privileged access rights",
          "implementation": "Privileged access controlled and monitored",
          "status": "implemented",
          "evidence": ["privileged_access_procedures", "monitoring_logs", "approval_records"]
        },
        "A.8.3": {
          "control": "Information access restriction",
          "implementation": "Access to information restricted based on business need",
          "status": "implemented",
          "evidence": ["access_control_policies", "authorization_matrices", "access_reviews"]
        },
        "A.8.4": {
          "control": "Access to source code",
          "implementation": "Access to source code controlled and logged",
          "status": "implemented",
          "evidence": ["source_code_access_logs", "developer_access_controls", "code_review_processes"]
        },
        "A.8.5": {
          "control": "Secure authentication",
          "implementation": "Multi-factor authentication implemented",
          "status": "implemented",
          "evidence": ["mfa_configuration", "authentication_logs", "password_policies"]
        },
        "A.8.6": {
          "control": "Capacity management",
          "implementation": "System capacity monitored and managed",
          "status": "implemented",
          "evidence": ["capacity_monitoring", "performance_reports", "scaling_procedures"]
        },
        "A.8.7": {
          "control": "Protection against malware",
          "implementation": "Anti-malware controls implemented and maintained",
          "status": "implemented",
          "evidence": ["antivirus_policies", "malware_detection_logs", "update_procedures"]
        }
      }
    }

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: iso27001-isms-review
  namespace: whatsdx-ai
  labels:
    compliance: iso27001
    type: isms-review
spec:
  schedule: "0 0 1 * *"  # Monthly on the 1st
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: isms-review
            image: whatsdx/iso27001-tools:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting ISO 27001 ISMS review..."
              
              # Risk assessment review
              node /app/scripts/risk-assessment-review.js
              
              # Control effectiveness review
              node /app/scripts/control-effectiveness.js
              
              # Security metrics collection
              node /app/scripts/security-metrics.js
              
              # Incident analysis
              node /app/scripts/incident-analysis.js
              
              # Performance monitoring
              node /app/scripts/isms-performance.js
              
              # Generate ISMS dashboard
              node /app/scripts/isms-dashboard.js
              
              echo "ISO 27001 ISMS review completed"
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: whatsdx-secrets
                  key: DATABASE_URL
            - name: ISO27001_COMPLIANCE_MODE
              value: "true"
            - name: ISMS_SCOPE
              value: "WhatsDeX AI Bot Information Processing System"
            volumeMounts:
            - name: iso27001-config
              mountPath: /app/config/iso27001
            - name: isms-documents
              mountPath: /app/isms
          volumes:
          - name: iso27001-config
            configMap:
              name: iso27001-compliance-config
          - name: isms-documents
            persistentVolumeClaim:
              claimName: iso27001-isms-pvc
          restartPolicy: OnFailure

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iso27001-isms-pvc
  namespace: whatsdx-ai
  labels:
    compliance: iso27001
    type: isms-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: encrypted-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iso27001-risk-management
  namespace: whatsdx-ai
  labels:
    app: iso27001-risk-management
    compliance: iso27001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iso27001-risk-management
  template:
    metadata:
      labels:
        app: iso27001-risk-management
        compliance: iso27001
    spec:
      containers:
      - name: risk-management
        image: whatsdx/iso27001-risk-management:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: ISO27001_COMPLIANCE_MODE
          value: "true"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: whatsdx-secrets
              key: DATABASE_URL
        - name: RISK_APPETITE
          value: "medium"
        - name: RISK_ASSESSMENT_FREQUENCY
          value: "annual"
        volumeMounts:
        - name: iso27001-config
          mountPath: /app/config/iso27001
        - name: risk-register
          mountPath: /app/risk-register
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: iso27001-config
        configMap:
          name: iso27001-compliance-config
      - name: risk-register
        persistentVolumeClaim:
          claimName: iso27001-isms-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: iso27001-risk-management-service
  namespace: whatsdx-ai
  labels:
    compliance: iso27001
    type: risk-management
spec:
  selector:
    app: iso27001-risk-management
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: iso27001-security-monitoring
  namespace: whatsdx-ai
  labels:
    compliance: iso27001
    type: security-monitoring
spec:
  groups:
  - name: iso27001.access_control
    rules:
    - alert: ISO27001UnauthorizedAccessAttempt
      expr: increase(failed_auth_attempts_total[5m]) > 5
      for: 1m
      labels:
        severity: warning
        compliance: iso27001
        control: "A.8.3"
      annotations:
        summary: "Unauthorized access attempts detected"
        description: "{{ $value }} failed authentication attempts in the last 5 minutes"
        
    - alert: ISO27001PrivilegedAccessUsage
      expr: increase(privileged_operations_total[1h]) > 10
      for: 1m
      labels:
        severity: info
        compliance: iso27001
        control: "A.8.2"
      annotations:
        summary: "High privileged access usage"
        description: "{{ $value }} privileged operations performed in the last hour"
        
  - name: iso27001.availability
    rules:
    - alert: ISO27001ServiceUnavailable
      expr: up{job="whatsdx-bot"} == 0
      for: 1m
      labels:
        severity: critical
        compliance: iso27001
        control: "A.8.6"
      annotations:
        summary: "Service unavailable"
        description: "WhatsDeX AI Bot service is down"
        
  - name: iso27001.integrity
    rules:
    - alert: ISO27001DataIntegrityBreach
      expr: increase(data_integrity_violations_total[5m]) > 0
      for: 1m
      labels:
        severity: critical
        compliance: iso27001
        control: "A.8.4"
      annotations:
        summary: "Data integrity violation detected"
        description: "Data integrity check failed {{ $value }} times"
        
  - name: iso27001.confidentiality
    rules:
    - alert: ISO27001UnauthorizedDataAccess
      expr: increase(unauthorized_data_access_total[5m]) > 0
      for: 1m
      labels:
        severity: critical
        compliance: iso27001
        control: "A.8.3"
      annotations:
        summary: "Unauthorized data access detected"
        description: "Attempted unauthorized access to confidential data"