# SOC 2 Type II Compliance Configuration for WhatsDeX AI Bot
# Service Organization Control 2 compliance framework

apiVersion: v1
kind: ConfigMap
metadata:
  name: soc2-compliance-config
  namespace: whatsdx-ai
  labels:
    compliance: soc2
    regulation: us
data:
  soc2-config.json: |
    {
      "soc2": {
        "enabled": true,
        "type": "Type II",
        "trustServicesCriteria": {
          "security": {
            "enabled": true,
            "principle": "System is protected against unauthorized access",
            "controls": [
              "access_controls",
              "logical_physical_access_controls",
              "system_operations",
              "change_management",
              "risk_mitigation"
            ]
          },
          "availability": {
            "enabled": true,
            "principle": "System is available for operation and use",
            "slaTarget": "99.9%",
            "controls": [
              "performance_monitoring",
              "online_monitoring",
              "backup_recovery",
              "incident_management"
            ]
          },
          "processing_integrity": {
            "enabled": true,
            "principle": "System processing is complete, valid, accurate, timely, and authorized",
            "controls": [
              "data_validation",
              "error_handling",
              "process_monitoring",
              "quality_assurance"
            ]
          },
          "confidentiality": {
            "enabled": true,
            "principle": "Information designated as confidential is protected",
            "controls": [
              "data_classification",
              "encryption",
              "access_restrictions",
              "confidentiality_agreements"
            ]
          },
          "privacy": {
            "enabled": false,
            "principle": "Personal information is collected, used, retained, disclosed, and disposed of in conformity with commitments",
            "note": "Enable if processing personal information"
          }
        },
        "organizationalStructure": {
          "securityOfficer": "security@yourdomain.com",
          "complianceOfficer": "compliance@yourdomain.com",
          "incidentResponseTeam": "incident@yourdomain.com"
        },
        "riskAssessment": {
          "frequency": "annual",
          "methodology": "NIST",
          "lastAssessment": "2024-01-01",
          "nextAssessment": "2025-01-01"
        },
        "auditRequirements": {
          "auditFrequency": "annual",
          "auditFirm": "Your Audit Firm",
          "reportingPeriod": "12 months",
          "evidenceRetention": "7 years"
        }
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: soc2-security-controls
  namespace: whatsdx-ai
  labels:
    compliance: soc2
    type: security-controls
data:
  security-controls.json: |
    {
      "accessControls": {
        "CC6.1": {
          "description": "Logical and physical access controls",
          "implementation": {
            "multiFactorAuthentication": true,
            "roleBasedAccess": true,
            "privilegedAccess": "monitored",
            "accessReview": "quarterly",
            "accountProvisioning": "automated",
            "accountDeprovisioning": "immediate"
          },
          "evidence": [
            "access_control_policies",
            "user_access_reviews",
            "privileged_access_logs",
            "mfa_configuration"
          ]
        },
        "CC6.2": {
          "description": "Authentication and authorization",
          "implementation": {
            "strongAuthentication": true,
            "passwordPolicy": {
              "complexity": "high",
              "rotation": "90 days",
              "history": "12 passwords"
            },
            "sessionManagement": "secure",
            "authorizationMatrix": "defined"
          }
        },
        "CC6.3": {
          "description": "System access is removed when no longer required",
          "implementation": {
            "automaticDisabling": "30 days",
            "terminationProcess": "immediate",
            "accessRecertification": "quarterly",
            "emergencyAccess": "monitored"
          }
        }
      },
      "systemOperations": {
        "CC7.1": {
          "description": "System capacity and performance monitoring",
          "implementation": {
            "capacityPlanning": true,
            "performanceMonitoring": "24/7",
            "alerting": "automated",
            "scalingPolicies": "defined"
          }
        },
        "CC7.2": {
          "description": "System monitoring and incident detection",
          "implementation": {
            "logMonitoring": "real-time",
            "anomalyDetection": true,
            "incidentResponse": "automated",
            "forensicLogging": true
          }
        }
      },
      "changeManagement": {
        "CC8.1": {
          "description": "Change management policies and procedures",
          "implementation": {
            "changeApproval": "required",
            "testingRequirements": "mandatory",
            "rollbackProcedures": "defined",
            "changeDocumentation": "complete"
          }
        }
      },
      "riskMitigation": {
        "CC9.1": {
          "description": "Risk identification and assessment",
          "implementation": {
            "riskAssessment": "annual",
            "threatModeling": "quarterly",
            "vulnerabilityScanning": "weekly",
            "penetrationTesting": "annual"
          }
        }
      }
    }

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: soc2-evidence-collection
  namespace: whatsdx-ai
  labels:
    compliance: soc2
    type: evidence-collection
spec:
  schedule: "0 0 * * 0"  # Weekly on Sunday at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: soc2-evidence
            image: whatsdx/soc2-compliance-tools:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting SOC 2 evidence collection..."
              
              # Collect access logs
              node /app/scripts/collect-access-logs.js --period=weekly
              
              # Generate security reports
              node /app/scripts/security-control-evidence.js
              
              # Collect system monitoring data
              node /app/scripts/collect-monitoring-evidence.js
              
              # Generate availability reports
              node /app/scripts/availability-evidence.js
              
              # Collect change management evidence
              node /app/scripts/change-management-evidence.js
              
              # Archive evidence
              node /app/scripts/archive-evidence.js --date=$(date +%Y-%m-%d)
              
              echo "SOC 2 evidence collection completed"
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: whatsdx-secrets
                  key: DATABASE_URL
            - name: SOC2_COMPLIANCE_MODE
              value: "true"
            - name: EVIDENCE_RETENTION_YEARS
              value: "7"
            volumeMounts:
            - name: soc2-config
              mountPath: /app/config/soc2
            - name: evidence-storage
              mountPath: /app/evidence
          volumes:
          - name: soc2-config
            configMap:
              name: soc2-compliance-config
          - name: evidence-storage
            persistentVolumeClaim:
              claimName: soc2-evidence-pvc
          restartPolicy: OnFailure

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soc2-evidence-pvc
  namespace: whatsdx-ai
  labels:
    compliance: soc2
    type: evidence-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: encrypted-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soc2-monitoring-dashboard
  namespace: whatsdx-ai
  labels:
    app: soc2-monitoring
    compliance: soc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soc2-monitoring
  template:
    metadata:
      labels:
        app: soc2-monitoring
        compliance: soc2
    spec:
      containers:
      - name: soc2-dashboard
        image: whatsdx/soc2-dashboard:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: SOC2_COMPLIANCE_MODE
          value: "true"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: whatsdx-secrets
              key: DATABASE_URL
        volumeMounts:
        - name: soc2-config
          mountPath: /app/config/soc2
        - name: evidence-storage
          mountPath: /app/evidence
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: soc2-config
        configMap:
          name: soc2-compliance-config
      - name: evidence-storage
        persistentVolumeClaim:
          claimName: soc2-evidence-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: soc2-monitoring-service
  namespace: whatsdx-ai
  labels:
    compliance: soc2
    type: monitoring-service
spec:
  selector:
    app: soc2-monitoring
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: soc2-compliance-alerts
  namespace: whatsdx-ai
  labels:
    compliance: soc2
    type: alerting-rules
spec:
  groups:
  - name: soc2.availability
    rules:
    - alert: SOC2AvailabilityBreach
      expr: up{job="whatsdx-bot"} < 0.999
      for: 1m
      labels:
        severity: critical
        compliance: soc2
      annotations:
        summary: "SOC 2 availability SLA breach detected"
        description: "System availability has fallen below 99.9% SLA requirement"
        
  - name: soc2.security
    rules:
    - alert: SOC2UnauthorizedAccess
      expr: increase(failed_logins_total[5m]) > 10
      for: 1m
      labels:
        severity: warning
        compliance: soc2
      annotations:
        summary: "Potential unauthorized access attempt"
        description: "Multiple failed login attempts detected"
        
    - alert: SOC2PrivilegedAccessUsage
      expr: increase(privileged_access_total[1h]) > 5
      for: 1m
      labels:
        severity: info
        compliance: soc2
      annotations:
        summary: "Privileged access usage detected"
        description: "Privileged access has been used {{ $value }} times in the last hour"