name: Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run security audit
        run: npm run security-audit
      - name: Check for critical vulnerabilities
        run: |
          if npm audit --audit-level=moderate --json | jq '.auditReport.vulnerabilities.critical > 0' 2>/dev/null || [ $? -eq 1 ]; then
            echo "Critical vulnerabilities found. Failing build."
            exit 1
          fi
          echo "No critical vulnerabilities found."